server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    compatibility-verifier:
      enabled: false

    discovery:
      client:
        simple:
          instances:
            auth-service:
              - uri: http://localhost:8081

            cep-service:
              - uri: http://localhost:8082

            produto-service:
              - uri: http://localhost:8083

    gateway:

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, NOT_FOUND
            methods: GET, PUT, DELETE
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: true

      routes:

        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/fatec/auth/**

        - id: produto
          uri: lb://produto-service
          predicates:
            - Path=/fatec/produtos/**

        - id: cep
          uri: lb://cep-service
          predicates:
            - Path=/fatec/cep/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG