server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    compatibility-verifier:
      enabled: false

    discovery:
      client:
        simple:
          instances:
            login-service:
              - uri: http://localhost:8081

            cliente-service:
              - uri: http://localhost:8082

            cep-service:
              - uri: http://localhost:8083

            produto-service:
              - uri: http://localhost:8084

    gateway:
      routes:

        - id: login
          uri: lb://login-service
          predicates:
            - Path=/fatec/login/**

        - id: cliente
          uri: lb://cliente-service
          predicates:
            - Path=/fatec/clientes/**

        - id: produto
          uri: lb://produto-service
          predicates:
            - Path=/fatec/produtos/**

        - id: cep
          uri: lb://cep-service
          predicates:
            - Path=/fatec/cep/**

      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, NOT_FOUND
            methods: GET, POST
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG